### ISSUE TITLE
Gallery: add an iframe mode for demos

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#10]
Some full-width components are now responsive and should be rendered in an iframe to make the media queries work properly.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x61ca6f1dbb747fc4f8f18b14a271dd9eaafebc88df66c4eda67f18309da2173d](https://etherscan.io/tx/0x61ca6f1dbb747fc4f8f18b14a271dd9eaafebc88df66c4eda67f18309da2173d)

**Comment by kdichev** [comment]
Can I get a bit more information about this issue? Which components are you refering with "some" in particular.

**Comment by sohkai** [comment]
The best case would be to render every demo in an resizable iframe, kind of like what they have at Shopify's Polaris (see e.g. their [Collapsible](https://polaris.shopify.com/components/behavior/collapsible#navigation) component).

Specifically, we have the `SidePanel` component as well as a few components using `<Breakpoint>` that should be rendered in an iframe.

**Comment by kdichev** [comment]
@sohkai I suspect that we would want to build our own Aragon iframe component and not depend on an external dependency component?

**Comment by kdichev** [comment]
I did a simple implementation using an react component `react-frame-component`.

**Comment by sohkai** [comment]
Awesome, thanks for submitting the PR! We haven't had a lot of time lately to check on PRs, but we'll get to them soon :).

I had no idea portals could be used cross-context like this, that's super neat!
