### ISSUE TITLE
Gallery: add installation instructions

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#110]

**Comment by cjyabraham** [comment]
There are instructions [here](https://hack.aragon.org/docs/aragonui-intro.html).  Do you mean you want these added to https://ui.aragon.org/ ?

**Comment by luisivan** [comment]
I'd say it's just for running the gallery locally, as opposed to having it in the dev docs?

**Comment by bpierre** [comment]
Closing as the aragonUI website is going to change.
