### ISSUE TITLE
Hookify all the things

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#136]
E.g. `SidePanel` could pass down `opened` via a render prop, most HOCs should have a render prop equivalent exposed.

**Comment by bpierre** [comment]
Updated the title to have hooks instead: a render prop component can be done in one line from a hook (but a hook can not be made from a render prop component).

I think we should even stop exporting render props for new things, to avoid any confusion.

**Comment by bpierre** [comment]
Closing since https://github.com/aragon/aragon-ui/issues/136 exists already

**Comment by sohkai** [comment]
Haha I think this **is** #136 :).

**Comment by bpierre** [comment]
haha sorry I meant https://github.com/aragon/aragon-ui/issues/357
