### ISSUE TITLE
Create a provider-like component to connect to Aragon.js

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-ui#142]
It could be cool if we had a provider-like component (think react-redux) to connect components more easily to Aragon.js.

We could explore what Truffle did in [drizzle-react](https://github.com/trufflesuite/drizzle-react).

This is a tomorrow issue.

**Comment by sohkai** [comment]
I use my [`observe`](https://github.com/aragon/aragon-ui/blob/master/src/rxjs/observe.js) a lot for this, in connecting the front-ends to the cache.
