### ISSUE TITLE
Autocomplete component

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-ui#149]
It would be nice to have an autocomplete feature for e.g. address fields, displaying different entities and apps in and outside your organisation.

I imagine something like this (excuse the non-jpg):

```
╔══════════════════════════════════╗
║ 0xdeadbeef                       ║ <- What you type
╞══════════════════════════════════╡
│ 0xdeadbeef                       │ <- Autocomplete of what you type
├──────────────────────────────────┤
│ APPS                             │ <- Label
│ Permissions (0xddadbeef)         │ <- Apps in DAO
├──────────────────────────────────┤
│ ENTITIES                         │ <- Label
│ satoshi.aragonid.eth (0xdddbeef) │ <- Interesting entities in DAO
└──────────────────────────────────┘
```

**Comment by izqui** [comment]
I love this. This could totally be part of the address input component we have been talking about. We should talk about how we could build the backend for this is aragon.js, which would require full, both ways, aragon-id support.

**Comment by onbjerg** [comment]
Yeah. I thought about wanting to do the permissions app today, but in the mockup there's a lack of flexibility for the input fields - they're all dropdowns, but should probably be a hybrid between an autocomplete field and a dropdown, or at least only autocomplete.

**Comment by luisivan** [comment]
Closing this since the PR is already sent and this issue doesn't add much now being open
