### ISSUE TITLE
Enhancements to label style

### ISSUE THREAD

**Issue by stellarmagnet** [aragon/aragon-ui#151]
I recommend:

* Removing the ":" from all field labels (this colon is not really necessary - there seems to be inconsistency of where a ':' is used - for example, look at the New Vote panel)
* Moving the asterisk for required fields closer to the label (easier for readability)

**Example of before & after**

![image](https://user-images.githubusercontent.com/2584493/38336790-e6453f42-3817-11e8-9af5-37add929a215.png)

**Comment by bpierre** [comment]
Agree with both propositions, the asterisk not being next to the word doesn’t feel right. I think it should also correspond to a footnote message (e.g. “These fields are required”). Thoughts @jounih?

**Comment by jounih** [comment]
Agreed, makes total sense. Thanks for the suggestion @stellarmagnet !

**Comment by sohkai** [comment]
Fixed with the new Fields in aragonUI 1.0.0.
