### ISSUE TITLE
AragonApp: in publicUrl, add a final / if not present

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#190]

**Comment by sohkai** [comment]
❤️ I remember this tripping me up a long time ago in https://github.com/aragon/aragon-ui/pull/18#discussion_r154487770

**Comment by Huanzhang89** [comment]
Would any of the other apps require this check too? Thinking whether to just add the check within `AragonApp.js` or add it in `utils`

**Comment by bpierre** [comment]
Yes I think it would make sense to have a `addSlash()` function in `utils`, probably in `utils/url.js`, in case we need it somewhere else.

**Comment by sohkai** [comment]
Fixed with #197.
