### ISSUE TITLE
EmptyStateCard: Migration from Flow introduced inconsistences with PropTypes.node in actionButton and icon props

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-ui#196]
### Background
The React [prop-types Readme](https://github.com/facebook/prop-types) says:
````js
  // Anything that can be rendered: numbers, strings, elements or an array
  // (or fragment) containing these types.
  optionalNode: PropTypes.node,
````

"Anything that can be rendered" should mean anything that can be put in the render method.

### ActionButton Problem
The problem is located in the defaultProps here: [actionButton defaultProp](https://github.com/aragon/aragon-ui/blob/master/src/components/Card/EmptyStateCard.js#L63)
````js
actionButton: StyledActionButton,
````

It generates this warning:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/5030059/43352072-05948456-921e-11e8-8811-bd5f39f9863d.png">
**Note that this happens even when no actionButton prop is provided (since the defaultProp is wrong)**

### ActionButton Solution
It should be replaced by:
````js
actionButton: <StyledActionButton />,
````

To make `StyledActionButton` a node element and therefore pass the proptype checking.

This solution breaks the render method, since then we are trying to render a node inside a node, imagine something like `<<ActionButton /> ...props </<ActionButton />>`

Affected [lines 46-48](https://github.com/aragon/aragon-ui/blob/master/src/components/Card/EmptyStateCard.js#L46) should be replaced by something like:
````js
      {React.cloneElement(
        ActionButton,
        { mode: 'strong', onClick: onActivate },
        actionText
      )}
````
### Icon Problem
The same happens for the icon prop, [line 39](https://github.com/aragon/aragon-ui/blob/master/src/components/Card/EmptyStateCard.js#L39)

### Icon Solution
The render method should be corrected to:
````js
      {Icon}
````

And be careful to pass a valid React.node as a prop, like this:
`` <EmptyStateCard icon={<IconHome />} />``

Anyway the current propTypes configuration for this component does not check if the prop is really an icon or a button in the actionButton case, but at least the React warnings are fixed with these changes.

### Usage example Problem
Finally, the Usage example is also wrong, since it is passing a function as the icon prop instead of a valid node, generating this warning:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/5030059/43352178-f5deafa8-921f-11e8-8b2c-3a6e32f22d88.png">

### Usage example Solution
It needs to be corrected to:
``icon={<IconEmpty color="blue" />}``

**Comment by ottodevs** [comment]
It also happens to the UI gallery page (look at the warnings in the console):
<img width="871" alt="image" src="https://user-images.githubusercontent.com/5030059/43352431-98d658c0-9223-11e8-99c4-2925cf8cab21.png">

Essentially every existent EmptyStateCard use is affected, since the usage docs are wrong: https://github.com/search?q=org%3Aaragon+EmptyStateCard&type=Code

Another solution should be changing the type of the affected props from `PropTypes.node` to `PropTypes.func` or even a custom PropType.

**Comment by ottodevs** [comment]
Ok, the problems seems to come from the Flow migration... in Flow stateless function components are considered nodes:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/5030059/43352680-b718ec5e-9227-11e8-9fce-31adc0b8fae2.png">
(See: https://flow.org/en/docs/react/types/#toc-react-node)

But in prop-types, it seems that functions never can be nodes.
For me the easier solutions is to change `PropTypes.node` to `PropTypes.func` in both icon and actionButton.

**Comment by bpierre** [comment]
Fixed by https://github.com/aragon/aragon-ui/pull/217, thanks @ottodevs!
