### ISSUE TITLE
Fix Countdown's datetime attribute

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#211]
Caused by `date-fns@2.0.0-beta.8`.

![image](https://user-images.githubusercontent.com/4166642/46626295-2f2e3f80-cb37-11e8-9a55-3f38a7d3a28e.png)

**Comment by deamme** [comment]
I checked this out and it seems like it has always been like that? How should it look?

**Comment by sohkai** [comment]
Fixed in #223
