### ISSUE TITLE
Firefox Windows glitches

### ISSUE THREAD

**Issue by parkovski** [aragon/aragon-ui#256]
I noticed a few UI glitches looking at the demo page on Firefox on Windows, which is my usual browser. These are the ones I noticed, although based on these it seems some more attention is needed for this particular setup. Sorry for the huge images, guessing this is yet another glitchy Windows behavior :angry:.

### Dropdown

![image](https://user-images.githubusercontent.com/1094150/48908414-6ef08280-ee6a-11e8-816f-b2913697bb14.png)

### Context menu

![image](https://user-images.githubusercontent.com/1094150/48908538-d3abdd00-ee6a-11e8-8bcf-9dc48aa24b74.png)

### Radio group

![image](https://user-images.githubusercontent.com/1094150/48908574-ede5bb00-ee6a-11e8-8e2c-c532fa5d728f.png)

**Comment by luisivan** [comment]
Interesting, thanks for reporting! What's your Firefox and Windows version?

**Comment by bpierre** [comment]
Thanks @parkovski! These three bugs were addressed in https://github.com/aragon/aragon-ui/pull/245, the gallery will be updated with the next release.

You can also ensure it’s fixed for you by running it locally:

```
git clone https://github.com/aragon/aragon-ui.git
cd aragon-ui && npm start
```

Then opening http://localhost:8080/

I am closing the issue, please reopen if it still doesn’t work for you :-)
