### ISSUE TITLE
Improve layout on mobile browsers

### ISSUE THREAD

**Issue by MidnightLightning** [aragon/aragon-ui#262]
The left sidebar is a persistent UI component and does not resize or rearrange on mobile browsers, making it very cumbersome to interact with Aragon Organizations on a mobile device.

Cipher browser in portrait mode:
![screenshot_20181202-110413_cipher](https://user-images.githubusercontent.com/250250/49342554-7a8a3900-f622-11e8-9de5-7f2d65c8537b.jpg)

----
Landscape mode isn't much better; there's still horizontal scrolling needed to see all the content:
![screenshot_20181202-110434_cipher](https://user-images.githubusercontent.com/250250/49342576-d5239500-f622-11e8-9d4f-cfc0a84189b3.jpg)

Interacting with that on mobile it took me quite a while to discover I needed to scroll all the way right to find the buttons to interact with the Token Manager.

**Comment by bpierre** [comment]
Hi, thanks for opening an issue!

Making Aragon better on mobile is definitely in our short term plans, and we have an issue to track the progress for it: https://github.com/aragon/aragon/issues/267

I am closing this issue as it is not going to be implemented in Aragon UI itself.
