### ISSUE TITLE
Stopwatch support for countdown

### ISSUE THREAD

**Issue by josx** [aragon/aragon-ui#263]
I am working on Payroll (an aragon future-app ) and using aragon-ui components (BTW great work!)

1) I have already created a new component called Timer that has the same logic that countdown, but it is a Stopwatch. (We need it because we need to show "Time since last XX" )
https://github.com/protofire/aragon-ui/commit/72d660c884b61de6dccbee635f9c963e7e759baa

2) In the other hand I have changed Countdown to suppor a new prop called: ```start```, if you send it, countdown will work as a stopwatch since date on start prop. (without loosing backwards compatibility)
https://github.com/protofire/aragon-ui/commit/7e8da33ccf52a3efa1f1808bb0e49ce79e24c7ba

### I would make a PR, but what do you prefer 1) or 2)

**Comment by bpierre** [comment]
Hi @josx! That’s great, we were just talking about it earlier this week with @drcmda, who is working on the notifications panel for the Aragon client: https://github.com/aragon/aragon/pull/495

For the PR, I would rather go for 2), renaming Countdown to something else. We could do something like this:

- Create a `Timer` component (or `Duration`?), supporting dates in the past and the future.
- We should keep the `CountDown` component for compatibility, but it would do nothing else than using the new component.

**Comment by josx** [comment]
Ok, I would refactor to have a new component that supports both behaviours and also keep backwards compatibility with Countdown component.

**Comment by bpierre** [comment]
Awesome, thanks! 👍

**Comment by drcmda** [comment]
That would be awesome, i would use it for notifications when it's ready.

**Comment by josx** [comment]
@bpierre Now you can review the PR ;)

**Comment by sohkai** [comment]
Closed by #264.
