### ISSUE TITLE
Optimize breakpoint component's mounting

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#281]
Currently the `Breakpoint` component forces its entire child tree to remount every time a breakpoint is passed. Ideally it'd be smarter about this, and only remount as needed.

**Comment by bpierre** [comment]
Related conversation: https://github.com/aragon/aragon/pull/539#discussion_r246906012

**Comment by bpierre** [comment]
Related PRs:

https://github.com/aragon/aragon-ui/pull/303
https://github.com/aragon/aragon/pull/601

**Comment by sohkai** [comment]
Closed by #303.
