### ISSUE TITLE
Create a better structure for utils

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#29]
`shared-utils` and `math-utils` should live under a `utils/` directory.

It would also be nice to move some of the related code in `shared-utils` to their own file, e.g. `a utils/styled/breakpoints.js`.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x9142b5c87c9f88ea8e67f5908330e8a2a8cd4ad799c50b607244c2a7caf5bcd8](https://etherscan.io/tx/0x9142b5c87c9f88ea8e67f5908330e8a2a8cd4ad799c50b607244c2a7caf5bcd8)

**Comment by monokh** [comment]
Mind if I pick this up? Seems like a nice little issue to get setup with the project 🙂

**Comment by sohkai** [comment]
@monokh Absolutely! We haven't funded the bounty yet, but we'll do so tomorrow.
