### ISSUE TITLE
Rename icons

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#32]
Opening an issue after having discussed this with @izqui.

Our [icon set](https://github.com/aragon/aragon-ui/pull/30) is composed of actions (notifications, wallet, …) and app icons (tokens, fundraising, …). Some icons used for apps are also used to represent actions. At the moment, their name is describing the app they represent.

This is the Identity app icon, which is named `IconIdentity`:

<img width="22" height="22" src="https://user-images.githubusercontent.com/36158/33497656-8924c1aa-d6c6-11e7-81ee-8d0c92822a0c.png">

You can see it being used in the Aragon menu:

<img width="243" alt="image" src="https://user-images.githubusercontent.com/36158/33497578-4b732fa4-d6c6-11e7-9e69-557db729196a.png">

And this same icon is also used as a “Transfer token” action in the Tokens app:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/36158/33497423-d0217a72-d6c5-11e7-86b8-3ec2d3203275.png">

- Icons names should describe what they represent in the most generic way, rather than the app they happen to represent (in the example above, it could be “user-add”).
- If an app is using an icon from the Aragon UI icon set, this app is free to duplicate it.

**Comment by izqui** [comment]
👍

Regarding app icons, for all `aragon-apps` we are probably fine having the icons in `aragon-ui`, but ideally apps would define their icon filename in the `manifest.json` and then we would load it.

**Comment by sohkai** [comment]
We'll be able to provide an icon path for `aragon-apps`' `manifest.json` since we need to copy over the assets from `aragon-ui` anyway. Better to dogfood.

**Comment by bpierre** [comment]
Closing as icon names are now coming from the design system.
