### ISSUE TITLE
Grid unit utility

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#333]
Historically, we’ve been using a `10px` base grid for most of the things, then started to introduce a `8px` grid for some things. In the future, we want to be using the `8px` grid only.

I think having a utility for this would help to make the transition to `8px` faster and easier to follow. There are of course many cases where we don’t want grid units. It is not about doing everything with it, but more as a convenience tool to make sure we use multiples of the grid unit when we want it. It would also help making a semantic distinction between e.g. `8px` when we want exactly `8px`, and `gu(1)` because we want to use one grid unit that happens to be `8px` too.

In the Aragon’s [App Center PR](https://github.com/aragon/aragon/pull/625), I started experimenting with using a constant to reinforce the grid unit we use for spacing:

```jsx
import { GU } from '../utils'
const App = () => <div css={`margin: ${GU}px ${4 * GU}px`} />
```

The problem is that it’s pretty verbose.

Another option would be to expose a function:

```jsx
import { gu } from '../utils'

const App = () => <div css={`margin: ${gu(1)}px ${gu(4)}px`} />

// We could even add `px` by default:

const App = () => <div css={`margin: ${gu(1)} ${gu(4)}`} />
```

But it’s still quite verbose. It would also add a lot of function calls, but it probably doesn’t have any significant impact on modern JS engines.

Another solution to make it less verbose could be to [extend](https://github.com/Losant/styled-transform-proxy) the way styled-components transforms styles to add a custom syntax:

```jsx
// As a CSS unit
const App = () => <div css="margin: 1gu 4gu" />

// As a CSS function
const App = () => <div css="margin: gu(1) gu(4)" />
```

Another solution could have been to use a [CSS variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) for it, but they are too verbose:

```jsx
const App = () => <div css="margin: calc(1 * var(--gu)) calc(4 * var(--gu))" />
```

## Proposal 1

As a first step:

- Make the `GU` constant available (`GU = 8`).
- Export a function named `g()` rather than `gu()` (shorter).
- `g()` would add `px` to the value, e.g. `g(2)` would return `16px`.

That way, we could use both GU and g() depending on what is needed. I don’t like the naming much, but they would be so common that I think conciseness is the most important aspect here. We could also have long name equivalents (`GRID_UNIT` and `gridUnit()`), but I don’t think they would be used at all.

It would means having this kind of syntax for now:

```jsx
import { AppBar, GU, g } from '@aragon/ui'

const App = () => (
  <AppBar padding={3 * GU}>
      <div css={`margin: ${g(1)} ${g(4)}`} />
  </AppBar>
)
```

Later, we could add:

- A babel transform to remove these function calls: `g(x)` => `(GU * x + 'px')`.
- A styled-components transform, to have the utility as a CSS function directly: `g(2)` => `16px`.

Which would two dependencies to use aragonUI in an optimal way: the styled-components transform (which would be a runtime dependency), and the babel transform, which would also make babel itself a recommended tool to build apps with aragonUI.

Same example with the styled-components transform:

```jsx
import { AppBar, GU } from '@aragon/ui'

const App = () => (
  <AppBar padding={3 * GU}>
      <div css="margin: g(1) g(4)" />
  </AppBar>
)
```

## Proposal 2

I wonder if we should try to use a function rather than the constant? I don’t like mixing the two, to achieve a very similar thing. I don’t think we should have a second parameter (too verbose), but maybe another function?

We could have `gp()` for “grid units in pixels”, and `gu()` for “grid units” (number).

Or `g()` for “grid units in pixels” (as it is the most commonly used), and `gn()` for “grid units as number”.

```jsx
import { AppBar, g, gn } from '@aragon/ui'

const App = () => (
  <AppBar padding={gn(3)}>
      <div css={`margin: ${g(1)} ${g(4)}`} />
  </AppBar>
)
```

With the styled transform:

```jsx
import { AppBar, g, gn } from '@aragon/ui'

const App = () => (
  <AppBar padding={gn(3)}>
      <div css="margin: g(1) g(4)" />
  </AppBar>
)
```

**Comment by sohkai** [comment]
Between the constant and the function, I like the function more. Proposal 2 sounds good; it still works with the babel transform if we let it be hard-coded to `8` (this number would be impossible to change without a major version release once start using it anyway), and `gn()` could be useful for math / etc.

**Comment by bpierre** [comment]
> it still works with the babel transform if we let it be hard-coded to `8` (this number would be impossible to change without a major version release once start using it anyway)

I’m more thinking about people using it from outside but yes I agree, this number should not be considered “dynamic”, even if it would make things easier if one day we decide to change it.

**Comment by bpierre** [comment]
@sohkai @delfipolito @AquiGorka Shall we go for this? Please vote with 👍 or 👎

```jsx
// shall we export this too?
const GRID_UNIT = 8

// gu() as in “grid unit”, this is the main function
const gu = (v = 1) => v * GRID_UNIT

// g() as in “grid unit for CSS”, but as short as possible 😆
const g = v => gu(v) + 'px'
```

Usage, without the styled transform:

```jsx
import { AppBar, g, gu } from '@aragon/ui'

const App = () => (
  <AppBar padding={gu(3)}>
      <div css={`margin: ${g(1)} ${g(4)}`} />
  </AppBar>
)
```

Usage with the styled transform:

```jsx
import { AppBar, gu } from '@aragon/ui'

const App = () => (
  <AppBar padding={gu(3)}>
      <div css="margin: g(1) g(4)" />
  </AppBar>
)
```

**Comment by bpierre** [comment]
It would come with some limitations, but `gu()` could also work as a template string:

```jsx
<div css={gu`margin: ${4} ${4} ${3}`} />
```

**Comment by AquiGorka** [comment]
My favorite: `const App = () => <div css="margin: 1gu 4gu" />` but this means a lot of changes with the preprocesor no?

In the meantime, I think the one I like the most (because it resembles 👆 ) is using a function.

Great work! ✨ ✨ ✨

**Comment by bpierre** [comment]
> My favorite: `const App = () => <div css="margin: 1gu 4gu" />` but this means a lot of changes with the preprocesor no?

Yes this syntax would be ideal, but would have to be done as a second step if we don’t want to spend too much time on it. We could either hook into how styled-components processes its styles (maybe using https://github.com/Losant/styled-transform-proxy, directly or as a base), or we could use a babel transform, based on [the styled-components plugin](https://github.com/styled-components/babel-plugin-styled-components).

> In the meantime, I think the one I like the most (because it resembles 👆 ) is using a function.

👌👌👌

**Comment by metamn** [comment]
If I understand well no `GU` or `gu` is exported yet from `@aragon/u`.

I mean I'm getting a `Attempted import error: 'GU' is not exported from '@aragon/ui'.`

Any other ways to access it? It would be nice to use it to make let's say spacing uniform.

Thanks!

**Comment by bpierre** [comment]
It shouldn’t be the case: https://codesandbox.io/s/sleepy-shockley-wtr74?fontsize=14

Maybe an issue with the configuration of your project? Could you try doing `cat node_modules/@aragon/ui/package.json | grep version` to confirm you are using the right version? Any issue trying to import the other components?

**Comment by metamn** [comment]
```
$cat node_modules/@aragon/ui/package.json | grep version
  "version": "1.0.0-alpha.32",
```
@bpierre Thanks for the quick answers :)

All other components can be imported so far, however I didn't try them all.

**Comment by bpierre** [comment]
Oh I see! `gu` is not exported, only `GU` is :smile:

**Comment by metamn** [comment]
The same for `GU` ... sorry :)

https://github.com/metamn/argn/blob/master/src/components/Blocks/Blocks.js

**Comment by bpierre** [comment]
It’s working here:

![image](https://user-images.githubusercontent.com/36158/67479691-e3293c80-f65e-11e9-9f49-cb071913dc4d.png)

Would you mind moving this conversation to aragon.chat? This issue is more about the initial proposal than the way `GU` currently works. You can find me in `#help` or message me directly: bpierre. Thanks! :pray:

**Comment by metamn** [comment]
Right! It was my machine ... restarted (khmmm ...;) and all works fine now! Thank you for the great help!

**Comment by sohkai** [comment]
We now export GU, and have an experimental babel plugin for making this easier to declare.
