### ISSUE TITLE
Missing components in gallery

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-ui#335]
The following components are missing in the gallery:

Providers:
  - [ ] PublicUrl
  - [ ] Root
  - [ ] Viewport

Icons:
  - [ ] ArrowDown
  - [ ] Bylaw
  - [ ] Close
  - [ ] Copy
  - [ ] Ellipsis

Components:
- [ ] AddressField
- [ ] BadgeNumber
- [ ] BaseStyles
- [ ] EthIdenticon
- [ ] ExternalLink
- [ ] FocusVisible
- [ ] IdentityBadge
- [ ] LineChart
- [ ] PartitionBar
- [ ] Timer
- [ ] TransactionBadge

**Comment by stellarmagnet** [comment]
This would be great too: https://github.com/aragon/aragon-apps/blob/master/apps/finance/app/src/components/ToggleContent.js

**Comment by francopetra** [comment]
Hi @bpierre, started working on this issue in this [branch](https://github.com/francopetra/aragon-ui/tree/gallery-update). 
@stellarmagnet The toggleContent you referenced should be added to the repo. All the other components are already in the repo and only need to be added to the Gallery, so I think it would be another Issue. Is there a process to include new components or can I just add it within this issue/PR?

**Comment by francopetra** [comment]
Update 

Providers:
🚫   PublicUrl
🚫  Root
🚫  Viewport

✅ Icons

Components:
✅  AddressField
✅  BadgeNumber
🚫  BaseStyles => What could be shown from the BaseStyles component in the Documentation?
✅  EthIdenticon
✅  ExternalLink
🚫  FocusVisible
✅  IdentityBadge
✅  LineChart
🚫  PartitionBar
🚫  Timer
🚫  TransactionBadge

**Comment by francopetra** [comment]
Not sure what is the purpose of PublicURL. Can anyone help me out so I can finish this issue?
Also, suggestions on how to document BaseStyles are welcomed.
@bpierre

Providers:
🚫 PublicUrl
✅Root
✅ Viewport

✅ Icons

Components:
✅ AddressField
✅ BadgeNumber
🚫 BaseStyles => What could be shown from the BaseStyles component in the Documentation?
✅ EthIdenticon
✅ ExternalLink
✅ FocusVisible
✅ IdentityBadge
✅ LineChart
✅ PartitionBar
✅ Timer
✅ TransactionBadge

**Comment by bpierre** [comment]
Hi @francopetra this is awesome, thank you! :heart: :heart: :heart: 

`PublicURL` is a component that is mostly used internally, it gives access to the base URL used to load assets (at the moment, the font files).

`BaseStyles` is really simple, so maybe it doesn’t require an example? Something that we might want to have would be a note explaining that it comes with `Main` automatically, so it’s kind of an advanced component.

Feel free to start opening the PR, even if it’s still in progress!

**Comment by francopetra** [comment]
Hey @bpierre, thanks for the guidance in that final part. Just opened the PR [#402](https://github.com/aragon/aragon-ui/pull/402).
Hope it can be merged and helps other devs!

**Comment by francopetra** [comment]
> Providers:
> 
> * [x]  PublicUrl
> * [x]  Root
> * [x]  Viewport
> 
> * [x] Icons:
> 
> * [x]  ArrowDown
> * [x]  Bylaw
> * [x]  Close
> * [x]  Copy
> * [x]  Ellipsis
> 
> Components:
> 
> * [x]  AddressField
> * [x]  BadgeNumber
> * [x]  BaseStyles
> * [x]  EthIdenticon
> * [x]  ExternalLink
> * [x]  FocusVisible
> * [x]  IdentityBadge
> * [x]  LineChart
> * [x]  PartitionBar
> * [x]  Timer
> * [x]  TransactionBadge

**Comment by bpierre** [comment]
Merged! :tada:  https://github.com/aragon/aragon-ui/pull/402
