### ISSUE TITLE
Identity Badge: rounded corners not properly rendered on iOS WebKit

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-ui#338]
Seems like both left corners of the Identity Badge are not getting properly rounded in mobile Safari and other apps that use iOS native WebKit webviews:

![image](https://user-images.githubusercontent.com/447328/54987330-b4f25a00-4fb4-11e9-9d8f-3d66db92cf03.png)

Tested on both Cipher and mobile Safari (iOS 12.0)

**Comment by izqui** [comment]
Just tested on iOS 12.1.4 on an iPad and can't reproduce the issue. Updating my other device to the latest iOS version to see if it was only an issue on previous versions.

**Comment by sohkai** [comment]
@izqui Could you retest on the latest version of the Aragon client?
