### ISSUE TITLE
Expand theme to have more colors

### ISSUE THREAD

**Issue by stellarmagnet** [aragon/aragon-ui#348]
Yellow or orange colors for (need brainstorming on this paradigm):
* warning 
* pending 

e.g. theme.pending (similar to theme.negative)

Rainbow palette for badgeAppBackground and badgeAppForeground:
* Tinted color for the bg, dark for fg: red, yellow, orange, green, teal, blue, pink, grey
* suggested names: badgeAppForegroundRed etc.

**Comment by sohkai** [comment]
Closing, we can add more colours to the theme based on specific requests.
