### ISSUE TITLE
Make `styled-components` a peerDependency?

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#35]
A consumer of this package could want to use their own instance (or version) of `styled-components`. It'd be nice if they could install and provide their own instance of `styled-components`.

**Comment by sohkai** [comment]
Limiting it to minor versions _should_ be fine; I assume the `styled-components` guys, of all people, know what the community expects from them in terms of version upgrades.

>  I’d like to limit as much as possible the number of dependencies people have to install in order to start an Aragon app.

Totally agree! Some of these more "fundamental" libraries we rely on and expect the user to have control over will likely be handled by @aragon/aragon-dev-cli's boilerplates (e.g. [react](https://github.com/aragon/aragon-react-boilerplate)) in the common use case.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xce62271ff15e2d0749b7c408e5ac5d7dfec8e80303822a3ecd872e5a96da9345](https://etherscan.io/tx/0xce62271ff15e2d0749b7c408e5ac5d7dfec8e80303822a3ecd872e5a96da9345)
