### ISSUE TITLE
Remove "provided not supported" message or at least make that verbosity optional

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-ui#367]
The message seems to be emitted from this line: https://github.com/aragon/aragon-ui/blob/f6dcd1b90d0758ab051c2404a8c646a17483caec/src/utils/web3.js#L22

For development purposes, would it make sense to remove that message or handle the localhost case independently?
As a developer I already know that localhost is not supported, but it is kind of annoying to debug actual error or warning messages when the browser console gets flood by that provider message...

![image](https://user-images.githubusercontent.com/5030059/57328195-0b54cb80-7111-11e9-973e-fd7b3217154c.png)

Also instead of pointing the etherscan link to localhost:3000 just point to etherscan or hide it at all when provider is not supported? Seems like bad UX and having the link there into the badge is not adding any value on those unsupported scenarios, another solution would be to just point to `#`

![image](https://user-images.githubusercontent.com/5030059/57328412-a8176900-7111-11e9-89b8-0cb75aac4fea.png)

**Comment by sohkai** [comment]
Agreed, we should just ignore localhost and hide the link in the IdentityBadge if no link could be formed.
