### ISSUE TITLE
Rollup configuration causes build scripts to fail, requires JSON plugin

### ISSUE THREAD

**Issue by gh1dra** [aragon/aragon-ui#400]
Here is the job that failed when trying to add the Markdown component: https://travis-ci.org/aragon/aragon-ui/jobs/553950501 

It's complaining about not knowing how to handle JSON files. I run into the same issue on my local machine.

**Comment by bpierre** [comment]
@gh1dra Do you still have the issue with the `newstyle` branch? It shouldn’t be importing JSON files from `node_modules` :thinking:

**Comment by gh1dra** [comment]
@bpierre Works like a charm on the `newstyle` branch, should I wait for that to get merged to `master` before rebasing? Closing #401

**Comment by sohkai** [comment]
We've since set `newstyle` as the default, and it will be merged onto `master` eventually.
