### ISSUE TITLE
New style DropDown: support the wide prop

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#416]
Needed at least for the SidePanel:

![image](https://user-images.githubusercontent.com/36158/61949644-c885ef80-afab-11e9-9f10-1677f3f54833.png)

It should follow the same type / default value than before:

https://github.com/aragon/aragon-ui/blob/master/src/components/DropDown/DropDown.js#L73
https://github.com/aragon/aragon-ui/blob/master/src/components/DropDown/DropDown.js#L79

**Comment by sohkai** [comment]
Fixed with https://github.com/aragon/aragon-ui/pull/436.
