### ISSUE TITLE
Add strong DropDown

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#44]
![image](https://user-images.githubusercontent.com/4166642/33647913-4eb16098-da25-11e7-8e10-47eacadd8a0e.png)

Could probably be done by adding a new prop to `DropDown` and applying some more styling.

**Comment by bpierre** [comment]
Another option would be to separate the menu part of `DropDown` (e.g. “`MenuPopup`”), so it can be used with a button.

**Comment by bpierre** [comment]
@dizzypaty @owisixseven I don’t think this DropDown variant is needed anymore?

**Comment by sohkai** [comment]
Closing as this dropdown variant isn't needed anymore.
