### ISSUE TITLE
Complete ProgressBar

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#46]
![image](https://user-images.githubusercontent.com/4166642/33648046-ffd6d4d4-da25-11e7-8af0-c285959b5c1f.png)
---------------
![image](https://user-images.githubusercontent.com/4166642/33648051-03f5d54c-da26-11e7-89eb-b18da16682ed.png)
----------------

(Actually this is a `ThresholdBar`; see #45):

![image](https://user-images.githubusercontent.com/4166642/33648056-07de00d0-da26-11e7-8ae9-ea832f548dfe.png)

**Comment by deamme** [comment]
Fixed by https://github.com/aragon/aragon-ui/pull/212?

**Comment by sohkai** [comment]
I think the first three screenshots are, and I just noticed the last one is more like the `ThresholdBar` in #45 so I've removed it from here :).

**Comment by sohkai** [comment]
ProgressBar is now available.
