### ISSUE TITLE
DropDown doesn't close when trigger is re-clicked

### ISSUE THREAD

**Issue by chadoh** [aragon/aragon-ui#477]
I observed this behavior with 1.0.0.alpha.9:

![dropdown click to close](https://user-images.githubusercontent.com/221614/63031418-ee533580-be81-11e9-8045-45f97268c17b.gif)

When clicking away, the dropdown closes correctly. When re-clicking the trigger, it closes and then quickly re-opens.

**Comment by bpierre** [comment]
It just got fixed! https://github.com/aragon/aragon-ui/pull/472
