### ISSUE TITLE
Add DateInput

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#51]
**Note**: we will likely want to include a two-panel `DateInput` as well.

-------

Normal:

![image](https://user-images.githubusercontent.com/4166642/33648428-d4b2b5fa-da27-11e7-8c65-9ad593d31d16.png)
-------------
Expanded:

![image](https://user-images.githubusercontent.com/4166642/33648431-d8c7b262-da27-11e7-976a-3002ab1b6a38.png)
------------
Range:

![image](https://user-images.githubusercontent.com/4166642/33648450-ebfa7eb4-da27-11e7-848f-682e7c1324b0.png)

Location: `src/Form/DateInput.js`
Potential components: [react-datepicker](https://github.com/Hacker0x01/react-datepicker), [react-dates](https://github.com/airbnb/react-dates), [react-day-picker](https://github.com/gpbl/react-day-picker)

**Comment by lmcorbalan** [comment]
Hi @sohkai
Who can provide with the necessary icon for these components?

![image](https://user-images.githubusercontent.com/3904914/49826188-11629e00-fd65-11e8-8a3e-8e59c1f7b28d.png)

**Comment by sohkai** [comment]
To be completed in https://github.com/aragon/aragon-ui/pull/623
