### ISSUE TITLE
DateRange: Support partial ranges

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-ui#514]
It would be nice to have the `DateRange` component optionally support partial ranges, e.g.:

1. A user only selects a start date - should be interpreted as "everything after this date"
2. A user only selects an end date - should be interpreted as "everything before this date"

I understand this might not be desired in every case, so I propose this should be hidden behind a boolean prop.

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon-ui/issues/627.
