### ISSUE TITLE
DataView: avoid closing an entry's children when accessing their actions

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#516]
See https://github.com/aragon/aragon/pull/899#discussion_r315156016 ([behaviour](https://imgur.com/z2vjHox))

**Comment by andy-hook** [comment]
This appears to occur only in the larger table mode and reacts to any state changes higher up in the tree. You can see this by spinning up a view and immediately expanding a row, as data is piped in it'll collapse without any intention from the user.

**Comment by andy-hook** [comment]
Fixed in https://github.com/aragon/aragon-ui/pull/810
