### ISSUE TITLE
Popover component broken on ui.aragon.org

### ISSUE THREAD

**Issue by listenaddress** [aragon/aragon-ui#524]
**Page**
https://ui.aragon.org/popover/

**Behavior**
When clicking the button in the popover demonstration, the screen goes blank and I get the `Cannot read property 'nodeName' of null` errors shown in the screenshot below. 

![Screen Shot 2019-08-22 at 11 09 49 AM](https://user-images.githubusercontent.com/8434548/63526553-96de4680-c4cd-11e9-9132-36986d68e9bb.png)

**Comment by bpierre** [comment]
Hi, thanks for reporting this! I published a new version that fixes the issue.
