### ISSUE TITLE
Add TimeText

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#55]
![image](https://user-images.githubusercontent.com/4166642/33648636-da783d2e-da28-11e7-9347-6feec02d3f11.png)
-----------
![image](https://user-images.githubusercontent.com/4166642/33648640-de887bf4-da28-11e7-9541-77e9b00824d1.png)

Location: `src/Text/TimeText.js`

**Comment by bpierre** [comment]
Fixed by https://github.com/aragon/aragon-ui/pull/90
