### ISSUE TITLE
Tag issue with text nodes

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#552]
It seems that `Tag` doesn’t behave properly in this situation:

```jsx
<Tag mode="identifier">
  {1} token{''}
</Tag>
```

@AquiGorka I let you complete if needed, as I haven’t tested it myself.

**Comment by AquiGorka** [comment]
I've found that [here](https://github.com/aragon/aragon-ui/blob/newstyle/src/components/Tag/Tag.js#L100) `children` (`Array`) gets casted to `String`.

**Comment by bpierre** [comment]
Yes we should only do that when it’s a number. :+1: 

We should also skip the [length check](https://github.com/aragon/aragon-ui/blob/newstyle/src/components/Tag/Tag.js#L130) when `children` are nodes.

**Comment by AquiGorka** [comment]
Actually I was testing, and we can remove the cast to `String` altogether, the only place where the length is used has a check for string: `finalLabel === 'string' && finalLabel.length < 2`

**Comment by bpierre** [comment]
Ah yes true, this part is already ok then. The only thing remaining would be to convert the numbers into strings, so we can use `.length` on single digits as well.

**Comment by AquiGorka** [comment]
These look fine:
![image](https://user-images.githubusercontent.com/3072458/64182581-bb8cd380-ce68-11e9-9305-66089c42761e.png)

**Comment by AquiGorka** [comment]
Is this what you are referring to:

![image](https://user-images.githubusercontent.com/3072458/64182739-f989f780-ce68-11e9-872d-5cda8c50fbd1.png)

**Comment by bpierre** [comment]
No I think we should move the `String()` here: https://github.com/aragon/aragon-ui/blob/newstyle/src/components/Tag/Tag.js#L96

(and also rename `formatedValue` => `formattedValue` :s)

**Comment by AquiGorka** [comment]
If we do that, then this will never happen: `typeof label === 'number'`

**Comment by bpierre** [comment]
It will, `label` is the passed value, not the formatted one.

**Comment by bpierre** [comment]
Fixed https://github.com/aragon/aragon-ui/pull/562
