### ISSUE TITLE
Add Form

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#58]
See most app side panels.

Location: `src/Form/Form.js`

**Comment by sohkai** [comment]
After taking a look around, I don't think we need to provide our own Form component.

AFAIK, the design language we're leading with in our own apps has all forms inside the sidepanel (as forms are "actionable"). In these sidebars, there's no additional styling needed to signify there's a form; placing input fields is enough. All a form provides is a state container and some validation logic for these inputs.

I'm a fan of [formik](https://github.com/jaredpalmer/formik), in comparison to other form helpers like [react-form](https://react-form.js.org/) and [formsy](https://github.com/formsy/formsy-react/), because of its simplicity and familiar API. It's closely based on the native `form` and `input` components and allows you to easily [plug in your own custom `input`s](https://github.com/jaredpalmer/formik#field-) (rather than forcing you to adhere to their own API or make vendor-specific custom `inputs`). Our own input components, like those in #67, will work transparently with `formik`.

I don't see much point in re-exporting it from this package; we can just include `formik` (or even another form implementation) whenever an app needs a form in its sidepanel. For other app developers, we can add a suggestion in a "tips and tricks" wiki or app tutorial later.

Thoughts @bpierre?

**Comment by bpierre** [comment]
Agree, `<form>` is behavioral and shouldn’t be provided by Aragon UI if possible.

> Our own input components, like those in #67, will work transparently with formik.

formik sounds good! I never tried it, but I remember having some difficulties to make styled components work with [react-formal](http://jquense.github.io/react-formal/) on a project.

If formik becomes our recommended solution to manage forms, maybe we should rename our `Field` component to something else (e.g. `FieldBlock`, `FieldSection`)?

**Comment by sohkai** [comment]
> If formik becomes our recommended solution to manage forms, maybe we should rename our `Field` component to something else (e.g. `FieldBlock`, `FieldSection`)?

Maybe `LabelledField`? The other two sound too "style-derived".

**Comment by sohkai** [comment]
Closing this, as we're not providing our own form element. Renaming can happen later, if we see the need to recommend formik.
