### ISSUE TITLE
DataView: heading prop padding on compact view

### ISSUE THREAD

**Issue by AquiGorka** [aragon/aragon-ui#603]
Reference: https://github.com/aragon/aragon/pull/1077#issuecomment-532612444

Update padding to `2gu` instead of `3gu`

I tagged you @bpierre and @dizzypaty to make sure this change is consistent with how we use `DataView` and when that is settled I'll submit the changes.

**Comment by dizzypaty** [comment]
Yes – 2GU for compact view and 3GU when displayed on large viewports. Thanks @AquiGorka!

![Group 3](https://user-images.githubusercontent.com/7205369/65255295-897ca200-daf5-11e9-90b5-d00ef4c51884.png)

**Comment by AquiGorka** [comment]
PR: https://github.com/aragon/aragon-ui/pull/605
