### ISSUE TITLE
How to use the new theme

### ISSUE THREAD

**Issue by carscx** [aragon/aragon-ui#607]
Hi,

There are some example for use the new feature Main Theme?
I tried 

```jsx
<Main theme="dark">
...
</Main>
```

```jsx
<Main>
<MainTheme theme="dark">
...
</MainTheme>
</Main>
```

But not work.

**Comment by bpierre** [comment]
Hi @carscx! Are you trying to use the theming system from an app? If so, the way to do it is by using `useTheme()`. `<MainTheme />` is a component meant to be used [internally](https://github.com/aragon/aragon-ui/blob/newstyle/src/components/Main/Main.js#L42).

Being able to switch from the light to the dark theme will soon be enabled from the client, and apps using aragonUI will be aware of it automatically.

The new system can be used like this from an app:

```jsx
import { Main, useTheme } from '@aragon/ui'

function MyAragonApp() {
  const theme = useTheme()
  return (
    <Main>
      <p style={{ color: theme.positive }}>
        The “positive” color of the current theme will be used here.
      </p>
    </Main>
  )
}
```

Let me know if you have any question!

**Comment by carscx** [comment]
Hi @bpierre ! 


Thanks for your answer. But what I thought when I saw the MainTheme component was that I could switch between one theme and another globally.

**Comment by bpierre** [comment]
Oh I see!

So you would have two options to do that:

- Use `Theme`.
- Change the theme defined by `MainTheme` using [`useThemeMode().set(theme)`](https://github.com/aragon/aragon-ui/blob/newstyle/src/theme/MainTheme.js#L18).

I would not recommend using the second option, as the main theme is really meant to always be synced with the client.

But there can be some cases where you’d want to have a specific theme applied to the components in a specific part of an app. For example, we could imagine a background image set by users, and components displayed over it. We could detect if this image is more dark or light, and use `Theme` to override the theme in this specific place:

```jsx
function MyApp() {
  return (
    <Main>
      <div style={{ background: '#333' }}>
        <Theme theme="dark">
          <Button>
            This button always uses the dark theme (and stops being synced with the client).
          </Button>
        </Theme>
      </div>
      
      <Button>
        This button uses the current theme (synced with the client).
      </Button>
    </Main>
  )
}
```

**Comment by carscx** [comment]
Ok, I have already understood.

Thank you so much for everything

**Comment by bpierre** [comment]
You’re welcome! I’m closing this issue, don’t hesitate to ask if you have any other question 🙂
