### ISSUE TITLE
Fixing README.md / Quick Setup

### ISSUE THREAD

**Issue by metamn** [aragon/aragon-ui#618]
In order to make the Quick Setup work in README.md https://github.com/aragon/aragon-ui#quick-setup the following lines has to be added to the docs:

```
npm install --save styled-components
```

or 

```
yarn add styled-components
```

And the `App.js` should look like:

```
import React from 'react';
import { Main } from '@aragon/ui'

const App = () => (
  <Main>
    <h1>Hello aragonUI!</h1>
  </Main>
)
```

That would make the Quick Start work out of the box. Tested with Create React App.

**Comment by bpierre** [comment]
Hi @metamn, thanks for opening an issue! I was trying to keep it to the minimum even if some things were missing, but you’re right that adding a second module to install + one line of import doesn’t make it that more verbose. :+1:
