### ISSUE TITLE
Add a TopBarPage component?

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#63]
Discussion started in this PR: https://github.com/aragon/aragon/pull/68#discussion_r155681614

@sohkai What do you think?

**Comment by sohkai** [comment]
Agreed, `StyledAppBar` could be repurposed into its own component and then `AppBar` could extend it for the menu bar in apps.

--------------

> The scrollable view below it

I'm not sure I like this; would it then look something like:

```js
<TopBarPage header={...}>
  <Content />
</TopBarPage>
```

Where the children of `TopBarPage` would be rendered in the scrollable view?

**Comment by bpierre** [comment]
Yes, that’s how I was seeing it. But thinking more about it, I agree it’s not nice to expect nodes in a property that is not `children`.

We could have a series of components grouped together that would allow to create the different kinds of layouts we need.

```jsx
<AragonApp>
  <AragonApp.TopBar>
    {/* app header */}
  </AragonApp.TopBar>
  <AragonApp.Content>
    {/* app content */}
  </AragonApp.Content>
</AragonApp>
```

For the layout of the Home app, it would like like this:

```jsx
<AragonApp>
  <AragonApp.TopBar>
    <header>
      <h1>Welcome!</h1>
    </header>
  </AragonApp.TopBar>
  <AragonApp.Content>
    <h1>What do you want to do?</h1>
    …
  </AragonApp.Content>
  <AragonApp.SideBar>
    <aside>
      <h1>Your tokens</h1>
      …
    </aside>
  </AragonApp.SideBar>
  <AragonApp.Footer>
    <footer>
      ETH: $ 302,91   …
    </footer>
  </AragonApp.Footer>
</AragonApp>
```


We could also consider renaming `AragonApp.TopBar` to `AragonApp.Header`.

What do you think @sohkai?

**Comment by sohkai** [comment]
@bpierre I think this fits in perfectly with how we're namespacing the rest of the UI components. `TopBar` is probably a better name than `Header`, and, to go along with that, I prefer `BottomBar` to `Footer`.

**Comment by bpierre** [comment]
`AppView` is doing this now https://github.com/aragon/aragon-ui/pull/164
