### ISSUE TITLE
Gallery Bug: Content displays on top left when dropdown is clicked 

### ISSUE THREAD

**Issue by Evalir** [aragon/aragon-ui#670]
Hey aragon-ui contributors! Due to the 1.0 release (congrats! 🚀) I was checking out the gallery for the new/updated components and noticed a slight bug on the dropdown page: when you click the dropdown, its content is displayed on the top left. It seems to be caused by either the Frame / Resizable components that are rendered if the prop `container` is `true` on the `PageDemo` component. Setting it as `false` and removing the `Container` component on the demo seems to solve the issue. I've made a pull request with the solution I implemented. See #669 

An image of the issue:
<img width="1680" alt="Screen Shot 2019-11-20 at 10 51 44 PM" src="https://user-images.githubusercontent.com/26014927/69300023-7ca92700-0be8-11ea-8318-6a44961f7557.png">

**Comment by sohkai** [comment]
@Evalir I noticed this in a few other places as well (maybe IdentityBadge?) that were using the Popover. Maybe they have the same issue as in #669.

**Comment by Evalir** [comment]
@sohkai Yeah, I just went quickly over all of the components and I noticed this:

- The DateRangePicker component in the gallery seems to have the same issue (haven't looked at the code yet)
- The Root component in the gallery has another issue altogether: When you click on the first button (open modal in the local root) the container doesn't properly resize and scrolls; also, the second button stays over the modal. (This should be a new issue I believe)
- The Root Portal gallery component throws 404 and so the screen stays blank.

**Comment by bpierre** [comment]
Yeah I think we could just remove the iframe container when we don’t need responsiveness, and I think it looks better too :-)

**Comment by Evalir** [comment]
Alright! I'll be sending the PR for the DateRangePicker component soon. :-)
