### ISSUE TITLE
Add Toggle component

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#675]
It would be nice if we had a generic Toggle for showing / hiding components:

<img width="218" alt="Screen Shot 2019-11-22 at 2 27 10 AM" src="https://user-images.githubusercontent.com/4166642/69390475-9a9d8700-0ccf-11ea-9c94-b6d4700afbb4.png">

See https://github.com/aragon/aragon/blob/master/src/components/MenuPanel/MenuPanel.js#L142

**Comment by guidovizoso** [comment]
Hi! I'd like to tackle this issue. Is there any information you'd consider relevant to complete this task? Thanks in advance guys!

**Comment by bpierre** [comment]
@sohkai is this component being used inside of an app or only in the client? In both cases I think it might be useful to have a toggle component to be used with the side panel, but it should probably look more like the one we use in the Finance app?

**Comment by sohkai** [comment]
> Is this component being used inside of an app or only in the client?

Yes, the screenshot above was from the client but I wanted to use it inside Finance to have the same toggle between both of them.
