### ISSUE TITLE
SyncIndicator: new design

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#678]
Implement the new design of `SyncIndicator`:

![image](https://user-images.githubusercontent.com/36158/69891156-31260580-12d9-11ea-8a8e-787cf05a5d3c.png)

**Comment by guidovizoso** [comment]
Hi! I'd like to tackle this issue. I noticed you don't have a contributing.md file yet. Are there certain steps to follow or should I take my own apporoach?

Thanks in advance!

**Comment by bpierre** [comment]
Hi @guidovizoso, thanks for proposing your help!

No particular step to follow, you can find the design for it here: https://www.figma.com/file/CN2tjvQxLu6pHiWKqPVxWT/Feedback-indicators?node-id=0%3A1

You can ping @dizzypaty or @owisixseven for any design related question, but the easiest would probably be to come on aragon.chat (I am `bpierre` there) :smile: => https://aragon.chat/channel/dev-frontend

Let me know if you have any question!

**Comment by bpierre** [comment]
Done in https://github.com/aragon/aragon-ui/pull/683 \o/
