### ISSUE TITLE
copyfiles is missing

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-ui#698]
`node_modules/@aragon/toolkit/node_modules/lie/package.json` contains a `copyfiles` command.

This command is not available on Ubuntu 19.10. So it does not work.

`@aragon/toolkit@0.0.2`

**Comment by sohkai** [comment]
@vporton `copyfiles` is exposed by aragonUI, so you'll need to also `npm install -S @aragon/ui` to access it.

**Comment by vporton** [comment]
After `npm install -S @aragon/ui` in a project directory running `find -name copyfiles` shows nothing.

By the way, what is `-S`?

**Comment by bpierre** [comment]
Hi @vporton! The npm package `@aragon/toolkit` is not related to aragonUI despite the name. It is [a non-UI toolkit used by aragonCLI](https://github.com/aragon/aragon-cli/tree/master/packages/toolkit) (or “aragonCLI lib”).

Closing for now, please let us know if we should reopen.

**Comment by vporton** [comment]
@bpierre @sohkai I did on your suggestion both `npm install -S @aragon/ui` and `npm install -S @aragon/toolkit` but `find -name copyfiles `still finds nothing! Why have you closed the bug? How to install this command?

**Comment by bpierre** [comment]
@vporton The module you are referring to, `@aragon/toolkit`, is not related to aragonUI but to aragonCLI (`@aragon/cli`), which I believe is what you are trying to use?

If that’s the case, we should reopen this issue on the aragonCLI project: https://github.com/aragon/aragon-cli/issues/new/choose

**Comment by vporton** [comment]
@sohkai @bpierre sohkai said "copyfiles is exposed by aragonUI, so you'll need to also npm install -S @aragon/ui to access it." Is sohkai wrong? I am confused where to report.

**Comment by bpierre** [comment]
I think @sohkai was mistaking with [`copy-aragon-ui-assets`](https://github.com/aragon/aragon-ui/blob/master/bin/copy-aragon-ui-assets) which is exposed by aragonUI, but has nothing to do with aragonCLI.

> I am confused where to report.

You should report on the aragonCLI repository if that’s what you are trying to use. Are you having an issue with aragonCLI (command line program) or aragonUI (React UI toolkit)?
