### ISSUE TITLE
EscapeOutside: check if `onEscapeOutside()` is a function (or mark it as required)

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#713]
See https://sentry.io/share/issue/ab33395f341f45f6a2e01e5ded6454b6/ (most likely the onboarding modal?)

**Comment by dantehemerson** [comment]
Hi @sohkai, I like to work on this. What do you think would be the best option?

**Comment by sohkai** [comment]
@dantehemerson Given that `EscapeOutside` is pretty much only meant to call its `onEscapeOutside()`, let's mark the prop as required and we'll fix the prop type elsewhere.
