### ISSUE TITLE
Website: React error when trying to see the "TransactionProgress" example

### ISSUE THREAD

**Issue by Evalir** [aragon/aragon-ui#721]
When the `Show Component` button for the demo is clicked, React throws an error that causes the site to go completely blank, needing a full refresh. Seems like we're missing a prop or something, as when decoding the error, I got this:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by Jfelix61** [comment]
Tried production and development server and no problems. Also, published to Netlify to test and everything went well. Maybe a republish can fix it?

**Comment by Evalir** [comment]
Could be! I’ll check this out. :)

**Comment by bpierre** [comment]
Fixed by a republish :+1:
