### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Jfelix61** [aragon/aragon-ui#730]
Is adding tests something considered for the near future?

**Comment by bpierre** [comment]
Definitely! What kind of tests are you thinking about?

**Comment by Jfelix61** [comment]
I was considering unit tests with jest and [react-testing-library](https://github.com/testing-library/react-testing-library) for now, just to start getting coverage

**Comment by bpierre** [comment]
Sounds good, that’s the solution we were keeping an eye on! Do you want to give it a try on a single component for now, so we can discuss this further on the PR? Also I think we should use it with Jest since we are already using it for some utility functions.

**Comment by Jfelix61** [comment]
Great, I'll be taking care of it later!

**Comment by bpierre** [comment]
Closing since https://github.com/aragon/aragon-ui/pull/732 got merged!
