### ISSUE TITLE
Add Oasis to the "Projects using ..." list

### ISSUE THREAD

**Issue by PaulRBerg** [aragon/aragon-ui#783]
Doesn't [Oasis](https://oasis.app) also use the Aragon UI? The styling is strikingly similar:

<img width="1033" alt="Capture d’écran 2020-06-16 à 12 56 18" src="https://user-images.githubusercontent.com/8782666/84760830-417da380-afd1-11ea-9595-04869e93e202.png">

**Comment by sohkai** [comment]
Nope, pretty sure they're not! They've had that look even before we really had ours (late 2017 vs. our current one in mid-2019).

**Comment by PaulRBerg** [comment]
Ah, interesting.
