### ISSUE TITLE
Add ability to detect required input in Field

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-ui#87]
![image](https://user-images.githubusercontent.com/4166642/33648461-fa37dbc0-da27-11e7-8f36-98036749c728.png)

Should show a highlighted `*` if the child has `required`.

**Comment by kdichev** [comment]
<img width="348" alt="screen shot 2018-01-19 at 15 44 03" src="https://user-images.githubusercontent.com/12297753/35155989-b808eb74-fd2f-11e7-8df8-ed13977c96d9.png">

Is this what's needed if yes I can pull request the feature
@sohkai

**Comment by sohkai** [comment]
@kdichev Yup, you've got it :).

**Comment by kdichev** [comment]
@sohkai have pull requested the feature :)
