### ISSUE TITLE
Icons: replace the fixed colours with 'currentColor' and add defaults

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-ui#96]
See discussion here: https://github.com/aragon/aragon-ui/pull/89/files/8024413238e18db7478e97994bc18f0df02ef2da#r163332307

**Comment by sohkai** [comment]
@bpierre Repurposing this issue for the latest developments in the thread with `currentColor`: https://github.com/aragon/aragon-ui/pull/89#discussion_r165119055.

**Comment by bpierre** [comment]
Closing as new icons are going to be monochromatic.
